Task 40 tests and scripts were added
igorchupin/Selenium-WebDriverTask pull request #1
Opened 2021-08-08 08:19 UTC by igorchupin

Task 40 tests and scripts were added

2021-08-09 14:45 UTC, EugenBorisik requested changes

2021-08-09 14:45 UTC, EugenBorisik commented on src/test/java/HalfDownloadTest.java
> +        while (percent <=50);
Please create your custom ExpectedCondition

2021-08-09 14:45 UTC, EugenBorisik commented on src/test/java/MultiselectTest.java
> +public class MultiselectTest {
Format code in this class

2021-08-09 14:45 UTC, EugenBorisik commented on src/test/java/MultiselectTest.java
> +        }
Can you rewrite this code with usage of java stream api?

2021-08-09 14:45 UTC, EugenBorisik commented on src/test/java/TestsForAlerts.java
> +        ()-> assertEquals("You pressed OK!", driver.findElement(By.id("confirm-demo")).getText(),
Format code

2021-08-09 14:45 UTC, EugenBorisik commented on src/test/java/ListOfObjectTest.java
> +        }
Move this code in separate method, which has parameters and returning value

2021-08-09 14:45 UTC, EugenBorisik commented on src/test/java/ListOfObjectTest.java
> +        selectObject.selectByValue("25");
10

2021-08-09 14:45 UTC, EugenBorisik commented on src/test/java/ListOfObjectTest.java
> +        WebElement nextButton;
Remove

2021-08-09 14:45 UTC, EugenBorisik commented on src/test/java/ListOfObjectTest.java
> +                String humanName = new String(peopleListWeb.get(j).findElement(By.xpath(String.format("//tr[%s]//td[1]", j+1))).getText());
"new String" is not needed

2021-08-09 14:45 UTC, EugenBorisik commented on src/test/java/ListOfObjectTest.java
> +                String humanPosition = new String(peopleListWeb.get(j).findElement(By.xpath(String.format("//tr[%s]//td[2]", j+1))).getText());
"new String" is not needed

2021-08-09 14:45 UTC, EugenBorisik commented on src/test/java/ListOfObjectTest.java
> +                String humanoffice = new String(peopleListWeb.get(j).findElement(By.xpath(String.format("//tr[%s]//td[3]", j+1))).getText());;
"new String" is not needed

2021-08-09 14:45 UTC, EugenBorisik commented on src/test/java/ListOfObjectTest.java
> +                Integer age = new Integer(Integer.valueOf(peopleListWeb.get(j).findElement(By.xpath(String.format("//tr[%s]//td[4]", j+1))).getText()));
"new Integer" is not needed

2021-08-09 14:45 UTC, EugenBorisik commented on src/test/java/ListOfObjectTest.java
> +        List<WebElement> buttonsCount = driver.findElements(By.xpath("//a[@class='paginate_button '] | " +
Bad locator

2021-08-09 14:45 UTC, EugenBorisik commented on src/test/java/ListOfObjectTest.java
> +        for (int i = 1; i <= buttonsCount.size(); i++) {
Replace with foreach

2021-08-09 14:45 UTC, EugenBorisik commented on src/test/java/ListOfObjectTest.java
> +            for (int j = 0; j < peopleListWeb.size(); j++) {
Replace with foreach

2021-08-09 14:45 UTC, EugenBorisik commented on src/test/java/ListOfObjectTest.java
> +                String humanName = new String(peopleListWeb.get(j).findElement(By.xpath(String.format("//tr[%s]//td[1]", j+1))).getText());
Now it looks like "bad hack", correct code will be:
.findElement(By.xpath(".//td[1]"))

2021-08-09 17:40 UTC, igorchupin commented on src/test/java/HalfDownloadTest.java
> +        while (percent <=50);
Custom ExpectedCondition was created.
commit 48035613f843f33abbc671f222ddb3b35a6baa5d

2021-08-09 19:36 UTC, igorchupin commented on src/test/java/MultiselectTest.java
> +        }
Stream API was used
commit 76ea1fd590496a135d0a872a55b8c697dc71c2f2

2021-08-09 19:40 UTC, igorchupin commented on src/test/java/MultiselectTest.java
> +public class MultiselectTest {
I did it
commit 472c4dd27c36b2dc95ec03f816625444281a8a37

2021-08-10 06:15 UTC, igorchupin commented on src/test/java/TestsForAlerts.java
> +        ()-> assertEquals("You pressed OK!", driver.findElement(By.id("confirm-demo")).getText(),
Done.
commit 472c4dd27c36b2dc95ec03f816625444281a8a37

2021-08-10 07:06 UTC, igorchupin commented on src/test/java/ListOfObjectTest.java
> +        }
Now, this code is a separate method.
commit be71aed623305902303353b0aea54704256fb6b1

2021-08-10 07:07 UTC, igorchupin commented on src/test/java/ListOfObjectTest.java
> +                String humanName = new String(peopleListWeb.get(j).findElement(By.xpath(String.format("//tr[%s]//td[1]", j+1))).getText());
Removed.
commit be71aed623305902303353b0aea54704256fb6b1

2021-08-10 07:07 UTC, igorchupin commented on src/test/java/ListOfObjectTest.java
> +                String humanPosition = new String(peopleListWeb.get(j).findElement(By.xpath(String.format("//tr[%s]//td[2]", j+1))).getText());
Removed.
commit be71aed623305902303353b0aea54704256fb6b1

2021-08-10 07:07 UTC, igorchupin commented on src/test/java/ListOfObjectTest.java
> +                String humanoffice = new String(peopleListWeb.get(j).findElement(By.xpath(String.format("//tr[%s]//td[3]", j+1))).getText());;
Removed.
commit be71aed623305902303353b0aea54704256fb6b1

2021-08-10 07:08 UTC, igorchupin commented on src/test/java/ListOfObjectTest.java
> +                Integer age = new Integer(Integer.valueOf(peopleListWeb.get(j).findElement(By.xpath(String.format("//tr[%s]//td[4]", j+1))).getText()));
Removed.
commit be71aed623305902303353b0aea54704256fb6b1

2021-08-10 07:08 UTC, igorchupin commented on src/test/java/ListOfObjectTest.java
> +        List<WebElement> buttonsCount = driver.findElements(By.xpath("//a[@class='paginate_button '] | " +
Locator was changed.

2021-08-10 07:08 UTC, igorchupin commented on src/test/java/ListOfObjectTest.java
> +        for (int i = 1; i <= buttonsCount.size(); i++) {
Replaced with foreach.

2021-08-10 07:09 UTC, igorchupin commented on src/test/java/ListOfObjectTest.java
> +            for (int j = 0; j < peopleListWeb.size(); j++) {
Replaced with foreach.
commit be71aed623305902303353b0aea54704256fb6b1

2021-08-10 07:10 UTC, igorchupin commented on src/test/java/ListOfObjectTest.java
> +                String humanName = new String(peopleListWeb.get(j).findElement(By.xpath(String.format("//tr[%s]//td[1]", j+1))).getText());
This was changed. Thank you!
commit be71aed623305902303353b0aea54704256fb6b1

2021-08-10 07:10 UTC, igorchupin commented on src/test/java/ListOfObjectTest.java
> +        WebElement nextButton;
This was removed.
commit be71aed623305902303353b0aea54704256fb6b1

2021-08-10 07:11 UTC, igorchupin commented on src/test/java/ListOfObjectTest.java
> +        selectObject.selectByValue("25");
Value was changed.
commit be71aed623305902303353b0aea54704256fb6b1

2021-08-10 19:29 UTC, EugenBorisik requested changes

2021-08-10 19:29 UTC, EugenBorisik commented on src/test/java/HalfDownloadTest.java
> +                if (percent >= 50) return true;
Simplify: return percent >= 50;

2021-08-10 19:29 UTC, EugenBorisik commented on src/test/java/MultiselectTest.java
> +        Stream<WebElement> expected = selectedOptions.stream();
Remove this line

2021-08-10 19:29 UTC, EugenBorisik commented on src/test/java/MultiselectTest.java
> +        result = expected.allMatch(x -> x.getText().contains("Texas") || x.getText().contains("Washington")
selectedOptions.stream().allMatch(...

2021-08-10 19:29 UTC, EugenBorisik commented on src/test/java/MultiselectTest.java
> +        result = expected.allMatch(x -> x.getText().contains("Texas") || x.getText().contains("Washington")
Create collection of options (named expectedOptions f.e.) in any place before stream.
Then simplify:
selectedOptions.stream().map(WebElement::getText).allMatch(expectedOptions::contains);
And place this code just in assertTrue method

2021-08-10 19:29 UTC, EugenBorisik commented on src/test/java/MultiselectTest.java
> +        boolean result = false;
Remove

2021-08-10 19:29 UTC, EugenBorisik commented on src/test/java/ListOfObjectTest.java
> +}
Just want to provide you example for this task using only stream api:
```
public List<People> getEmployees(int age, int salary) {
    WebElement selectEntries = driver.findElement(By.xpath("//select[@name='example_length']"));
    Select selectObject = new Select(selectEntries);
    selectObject.selectByValue("10");

    String paginationButton = "//a[contains(@class, 'paginate_button') and text()='%d']";
    List<WebElement> paginationButtons = driver.findElements(By.cssSelector("span>a.paginate_button"));
    return IntStream.rangeClosed(1, paginationButtons.size())
        .mapToObj(i -> driver.findElement(By.xpath(String.format(paginationButton, i))))
        .map(toEmployeesOnCurrentPage(age, salary))
        .flatMap(Collection::stream)
        .collect(Collectors.toList());
  }

  private Function<WebElement, List<People>> toEmployeesOnCurrentPage(int age, int salary) {
    return button -> {
      button.click();

      List<WebElement> rows = driver.findElements(By.xpath("//table[@id='example']//tbody/tr"));
      return rows.stream()
          .map(row -> {
            String currentName = row.findElement(By.xpath(".//td[1]")).getText();
            String currentPosition = row.findElement(By.xpath(".//td[2]")).getText();
            String currentOffice = row.findElement(By.xpath(".//td[3]")).getText();
            Integer currentAge = Integer.valueOf(row.findElement(By.xpath(String.format(".//td[4]"))).getText());
            String currentSalary = row.findElement(By.xpath(".//td[6]")).getText();
            currentSalary = currentSalary.substring(1, currentSalary.length() - 2).replace(",", "");
            Integer salaryInt = Integer.valueOf(currentSalary);

            return new People(currentName, currentPosition, currentOffice, currentAge, salaryInt);
          })
          .filter(employee -> employee.getAge() > age && employee.getSalary() <= salary)
          .collect(Collectors.toList());
    };
  }
```

2021-08-12 06:35 UTC, igorchupin commented on src/test/java/HalfDownloadTest.java
> +                if (percent >= 50) return true;
This was changed.
commit 582e14338eba808c7b8b3e9cec8e8304f329e004

2021-08-12 06:40 UTC, igorchupin commented on src/test/java/ListOfObjectTest.java
> +}
Thank you I need to read more about streams =(((

2021-08-12 06:41 UTC, igorchupin commented on src/test/java/MultiselectTest.java
> +        boolean result = false;
Removed

2021-08-12 06:42 UTC, igorchupin commented on src/test/java/MultiselectTest.java
> +        Stream<WebElement> expected = selectedOptions.stream();
Removed

2021-08-12 06:49 UTC, igorchupin commented on src/test/java/MultiselectTest.java
> +        result = expected.allMatch(x -> x.getText().contains("Texas") || x.getText().contains("Washington")
Changed

2021-08-12 06:53 UTC, igorchupin commented on src/test/java/MultiselectTest.java
> +        result = expected.allMatch(x -> x.getText().contains("Texas") || x.getText().contains("Washington")
Cahnged

2021-08-16 15:04 UTC, EugenBorisik approved these changes

2021-09-07 07:20 UTC, merged